# Generated by Django 3.2.4 on 2021-06-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itil_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='closing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='response_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
