# Generated by Django 3.2.4 on 2021-06-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itil_app', '0002_auto_20210622_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
